sudo: false
language: go

go:
  - 1.5
  - tip

before_install:
  - go get golang.org/x/tools/cmd/cover

script:
  - go test -coverprofile=coverage.out
  - go tool cover -func=coverage.out
  - go test -coverprofile=coverage.out ./utmp/
  - go tool cover -func=coverage.out
